-- CreateTable
CREATE TABLE "Aide" (
    "content_id" TEXT NOT NULL,
    "titre" TEXT NOT NULL,
    "contenu" TEXT NOT NULL,
    "url_simulateur" TEXT,
    "url_source" TEXT,
    "url_demande" TEXT,
    "is_simulateur" BOOLEAN,
    "partenaires_supp_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "codes_postaux" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "codes_commune_from_partenaire" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "thematiques" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "montant_max" INTEGER,
    "echelle" TEXT,
    "besoin" TEXT,
    "besoin_desc" TEXT,
    "include_codes_commune" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "exclude_codes_commune" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "codes_departement" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "codes_region" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "codes_departement_from_partenaire" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "codes_region_from_partenaire" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "est_gratuit" BOOLEAN NOT NULL DEFAULT false,
    "date_expiration" TIMESTAMPTZ(3),
    "derniere_maj" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "VISIBLE_PROD" BOOLEAN NOT NULL DEFAULT true,
    "question_accroche" TEXT,
    "introduction" TEXT,
    "explication" TEXT,
    "conditions_eligibilite" TEXT,
    "equipements_eligibles" TEXT,
    "travaux_eligibles" TEXT,
    "montant" TEXT,
    "en_savoir_plus" TEXT,
    "description_courte" TEXT,

    CONSTRAINT "Aide_pkey" PRIMARY KEY ("content_id")
);
